name: flutter_cache_manager
description: Generic cache manager for flutter. Saves web files on the storages of the device and saves the cache info using sqflite.
version: 3.3.2
homepage: https://github.com/Baseflow/flutter_cache_manager/tree/develop/flutter_cache_manager
topics:
  - cache
  - cache-manager
environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  clock: ^1.1.0
  collection: ^1.17.0
  file: ^6.1.4
  flutter:
    sdk: flutter
  http: ^0.13.6
  path: ^1.8.2
  path_provider:
    git:
      url: https://gitee.com/openharmony-sig/flutter_packages.git
      path: packages/path_provider/path_provider
  rxdart: ^0.27.7
  sqflite:
    git:
      url: https://gitee.com/openharmony-sig/flutter_sqflite.git
      path: sqflite
  uuid: ^3.0.7

dev_dependencies:
  build_runner: ^2.0.0
  flutter_lints: ^2.0.3
  flutter_test:
    sdk: flutter
  mockito: ^5.0.0
